#!/bin/bash
#
# Installs homebrew

echo "Checking for Homebrew installation..."
if test ! $(which brew)
then
	echo "Installing homebrew"
	ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
	echo "Done installing homebrew"
fi

echo "Updating brew"
brew update

echo "Upgrading formulas"
brew upgrade

# Install grc and coreutils
echo " Installing grc, coreutils, and node " 
brew install grc coreutils
brew install node
echo " Done installing... "


echo "Cleaning up outdated versions from cellar"
brew cleanup

